---
- name: Create tour of clojure group
  become: true
  group:
    name: "{{ tour_user }}"
    state: present

- name: Create tour of clojure user
  become: true
  user:
    name: "{{ tour_user }}"
    state: present
    group: "{{ tour_user }}"

- name: Create tour of clojure directory
  become: true
  file:
    path: "{{ tour_directory }}"
    state: directory
    owner: "{{ tour_user }}"
    group: "{{ tour_user }}"
    mode: "0750"

- name: Template tour of clojure systemd service
  become: true
  template:
    src: tour-clj.service.j2
    dest: /etc/systemd/system/tour-clj.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemd | daemon-reload
    - tour | restart

- name: Template tour of clojure configuration
  become: true
  template:
    src: tour-clj.yml.j2
    dest: "{{ tour_config_path }}"
    owner: "{{ tour_user }}"
    group: "{{ tour_user }}"
    mode: "0644"
  notify:
    - tour | restart

# Note: not idempotent
# I will replace this by a true continous deployment system soon
- name: Download tour of clojure release
  become: true
  get_url:
    url: "{{ tour_url }}"
    dest: "{{ tour_directory }}/tour-of-clojure.jar"
    force: true
    owner: "{{ tour_user }}"
    group: "{{ tour_user }}"
    mode: "0640"
  notify: tour | restart

- name: start tour of clojure service
  become: true
  service:
    name: tour-clj
    state: started
    enabled: true
